### ISSUE TITLE
openssl

### ISSUE THREAD

**Issue by who-am-1** [osa1/tiny#114]
```
$ rustc --version
rustc 1.31.0-nightly (2c2e2c57d 2018-10-12)
```
I have installed on fresh ArchLinux:
- openssl 1.1.1-1
- openssl-1.0 1.0.2.p-1
```
...
 Compiling quote v0.6.8                                                                                                      
warning: In file included from cbits/termbox.c:19:                                                                             
warning: cbits/term.inl: In function ‘load_terminfo’:
warning: cbits/term.inl:239:36: warning: ‘%c’ directive output may be truncated writing 1 byte into a region of size between 0 and 4095 [-Wformat-truncation=]
warning:      snprintf(tmp, sizeof(tmp), "%s/%c/%s", path, term[0], term);
warning:                                     ^~
warning: cbits/term.inl:239:5: note: ‘snprintf’ output 4 or more bytes (assuming 4099) into a destination of size 4096
warning:      snprintf(tmp, sizeof(tmp), "%s/%c/%s", path, term[0], term);
warning:      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: cbits/term.inl:247:36: warning: ‘%x’ directive output may be truncated writing between 1 and 8 bytes into a region of size between 0 and 4095 [-Wformat-truncation=]
warning:      snprintf(tmp, sizeof(tmp), "%s/%x/%s", path, term[0], term);
warning:                                     ^~
warning: cbits/term.inl:247:32: note: using the range [0, 4294967295] for directive argument
warning:      snprintf(tmp, sizeof(tmp), "%s/%x/%s", path, term[0], term);
warning:                                 ^~~~~~~~~~
warning: cbits/term.inl:247:5: note: ‘snprintf’ output 4 or more bytes (assuming 4099) into a destination of size 4096
warning:      snprintf(tmp, sizeof(tmp), "%s/%x/%s", path, term[0], term);
warning:      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: redundant linker flag specified for library `dbus-1`                                                                  
                                                                                                                               
error: failed to run custom build command for `openssl v0.9.24`                                                                
process didn't exit successfully: `/home/user/build/tiny/target/release/build/openssl-0b71e7037dfed8c5/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

After update native-tls to 0.2.1 in Cargo.toml I have:

> error[E0599]: no method named `map_err` found for type `native_tls::TlsConnectorBuilder` in the current scope                  
>   --> src/stream/tls.rs:37:14                                                                                                  
>    |                                                                                                                           
> 37 |             .map_err(TlsError::TlsError)?                                                                                 
>    |              ^^^^^^^                                                                                                      
>                                                                                                                                
> error[E0599]: no variant named `Interrupted` found for type `native_tls::HandshakeError<_>` in the current scope               
>   --> src/stream/tls.rs:44:17                                                                                                  
>    |                                                                                                                           
> 44 |             Err(tls::HandshakeError::Interrupted(mid)) =>                                                                 
>    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `native_tls::HandshakeError<_>`                
>                                                                                                                                
> error[E0599]: no variant named `Interrupted` found for type `native_tls::HandshakeError<_>` in the current scope               
>   --> src/stream/tls.rs:76:25                                                                                                  
>    |                                                                                                                           
> 76 |                     Err(tls::HandshakeError::Interrupted(mid)) =>                                                         
>    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `native_tls::HandshakeError<_>`        
>                                                                                                                                
> error: aborting due to 3 previous errors                                                                                       
>                                                                                                                                
> For more information about this error, try `rustc --explain E0599`.                                                            
> error: Could not compile `tiny`.                                                                                               
> 
> To learn more, run the command again with --verbose.

**Comment by osa1** [comment]
Thanks for reporting. I bumped native-tls to 0.2.1. Could you try again after a `git pull` and let me know if that fixes the problem?

**Comment by who-am-1** [comment]
```
$ cargo build --release
warning: In file included from cbits/termbox.c:19:                                                                             
warning: cbits/term.inl: In function ‘load_terminfo’:
warning: cbits/term.inl:239:36: warning: ‘%c’ directive output may be truncated writing 1 byte into a region of size between 0 and 4095 [-Wformat-truncation=]
warning:      snprintf(tmp, sizeof(tmp), "%s/%c/%s", path, term[0], term);
warning:                                     ^~
warning: cbits/term.inl:239:5: note: ‘snprintf’ output 4 or more bytes (assuming 4099) into a destination of size 4096
warning:      snprintf(tmp, sizeof(tmp), "%s/%c/%s", path, term[0], term);
warning:      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: cbits/term.inl:247:36: warning: ‘%x’ directive output may be truncated writing between 1 and 8 bytes into a region of size between 0 and 4095 [-Wformat-truncation=]
warning:      snprintf(tmp, sizeof(tmp), "%s/%x/%s", path, term[0], term);
warning:                                     ^~
warning: cbits/term.inl:247:32: note: using the range [0, 4294967295] for directive argument
warning:      snprintf(tmp, sizeof(tmp), "%s/%x/%s", path, term[0], term);
warning:                                 ^~~~~~~~~~
warning: cbits/term.inl:247:5: note: ‘snprintf’ output 4 or more bytes (assuming 4099) into a destination of size 4096
warning:      snprintf(tmp, sizeof(tmp), "%s/%x/%s", path, term[0], term);
warning:      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Compiling tiny v0.4.3 (/home/user/build/tiny)                                                                               
    Finished release [optimized] target(s) in 44.45s
```

**Comment by osa1** [comment]
Great! Closing.
